name: Example Backend
on:
  push:
    branches: [main]
env:
  IMAGE_NAME: ${{ vars.DOCKER_USERNAME }}/example-backend
jobs:
  build-push:
    runs-on: ubuntu-latest
    env:
      REQUEST_ORIGIN: ${{ vars.EXAMPLE_BACKEND_REQUEST_ORIGIN }}
      REDIS_HOST: ${{ vars.EXAMPLE_BACKEND_REDIS_HOST }}
      POSTGRES_HOST: ${{ vars.EXAMPLE_BACKEND_POSTGRES_HOST }}
      POSTGRES_PASSWORD: ${{ secrets.EXAMPLE_BACKEND_POSTGRES_PASSWORD }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.9.0
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./material-applications/example-backend
          file: ./material-applications/example-backend/Dockerfile-proxy-deploy
          secrets: |
            "REQUEST_ORIGIN=$REQUEST_ORIGIN"
            "REDIS_HOST=$REDIS_HOST"
            "POSTGRES_HOST=$POSTGRES_HOST"
            "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=lc-2025/docker:main
          cache-to: type=inline
      - name: Log in to the Container registry
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    needs: build-push
    steps:
      - name: Deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"
